name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: v21.1.0
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Run tests
      run: yarn test
